Add Abby Abbie to Shanghai
ElaWorkshop/awesome-cn-cafe pull request #208
Opened 2021-08-14 08:19 UTC by shijieyao

2021-08-14 09:27 UTC, xavierchow commented
@shijieyao thank you for your PR! Could you please update the README file to bump up the number for Shanghai as well?


![image](https://user-images.githubusercontent.com/2748884/129441473-adb474cf-3fdf-4ffd-8bfe-f8980e8a7f50.png)

2021-08-14 09:32 UTC, shijieyao commented
@xavierchow  Done :D

2021-08-14 09:38 UTC, xavierchow requested changes

2021-08-14 09:38 UTC, xavierchow commented on shanghai.geojson
> +          31.200,
```suggestion
          31.200
```

2021-08-16 01:49 UTC, xavierchow approved these changes

2021-08-16 01:49 UTC, merged

2021-08-16 01:50 UTC, xavierchow commented
merging, thank you!